using System.Diagnostics;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json.Serialization;

namespace dev.Services;

public sealed class GitHubApiClient(HttpClient httpClient, ApiTelemetry telemetry)
{
    public Task<GitHubProfile?> GetProfileAsync(string username, CancellationToken cancellationToken = default) => GetJsonAsync<GitHubProfile>($"/users/{Uri.EscapeDataString(username)}", "GET /users/{user}", cancellationToken);
    public async Task<IReadOnlyList<GitHubRepository>> GetRepositoriesAsync(string username, int perPage = 12, CancellationToken cancellationToken = default) => await GetJsonAsync<IReadOnlyList<GitHubRepository>>($"/users/{Uri.EscapeDataString(username)}/repos?sort=updated&per_page={Math.Clamp(perPage,1,100)}", "GET /users/{user}/repos", cancellationToken) ?? [];
    public Task<GitHubRepository?> GetRepositoryAsync(string owner,string repository,CancellationToken cancellationToken=default)=>GetJsonAsync<GitHubRepository>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}","GET /repos/{owner}/{repo}",cancellationToken);
    public async Task<GitHubReadme?> GetReadmeAsync(string owner,string repository,CancellationToken cancellationToken=default){var readme=await GetJsonAsync<GitHubReadme>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/readme","GET /repos/{owner}/{repo}/readme",cancellationToken);if(readme?.Content is null)return readme;try{return readme with{DecodedContent=Encoding.UTF8.GetString(Convert.FromBase64String(readme.Content.Replace("\n","").Replace("\r","")))}}catch(FormatException){return readme;}}
    public async Task<GitHubFileContent?> GetFileContentAsync(string owner,string repository,string path,string reference,CancellationToken cancellationToken=default){var encodedPath=string.Join('/',path.Split('/',StringSplitOptions.RemoveEmptyEntries).Select(Uri.EscapeDataString));var file=await GetJsonAsync<GitHubFileContent>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/contents/{encodedPath}?ref={Uri.EscapeDataString(reference)}","GET /repos/{owner}/{repo}/contents/{path}",cancellationToken);if(file?.Content is null)return file;try{return file with{DecodedContent=Encoding.UTF8.GetString(Convert.FromBase64String(file.Content.Replace("\n","").Replace("\r","")))}}catch(FormatException){return file;}}
    public async Task<IReadOnlyList<GitHubCommit>> GetCommitsAsync(string owner,string repository,int perPage=5,CancellationToken cancellationToken=default)=>await GetJsonAsync<IReadOnlyList<GitHubCommit>>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/commits?per_page={Math.Clamp(perPage,1,20)}","GET /repos/{owner}/{repo}/commits",cancellationToken)??[];
    public Task<GitHubCommitDetail?> GetCommitAsync(string owner,string repository,string sha,CancellationToken cancellationToken=default)=>GetJsonAsync<GitHubCommitDetail>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/commits/{Uri.EscapeDataString(sha)}","GET /repos/{owner}/{repo}/commits/{sha}",cancellationToken);
    public Task<GitHubCompareResult?> CompareCommitsAsync(string owner,string repository,string baseSha,string headSha,CancellationToken cancellationToken=default)=>GetJsonAsync<GitHubCompareResult>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/compare/{Uri.EscapeDataString(baseSha)}...{Uri.EscapeDataString(headSha)}","GET /repos/{owner}/{repo}/compare",cancellationToken);
    public async Task<IReadOnlyList<GitHubPullRequest>> GetPullRequestsAsync(string owner,string repository,int perPage=5,CancellationToken cancellationToken=default)=>await GetJsonAsync<IReadOnlyList<GitHubPullRequest>>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/pulls?state=all&sort=updated&direction=desc&per_page={Math.Clamp(perPage,1,20)}","GET /repos/{owner}/{repo}/pulls",cancellationToken)??[];
    public async Task<IReadOnlyList<GitHubIssue>> GetIssuesAsync(string owner,string repository,int perPage=5,CancellationToken cancellationToken=default)=>await GetJsonAsync<IReadOnlyList<GitHubIssue>>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/issues?state=all&sort=updated&direction=desc&per_page={Math.Clamp(perPage,1,20)}","GET /repos/{owner}/{repo}/issues",cancellationToken)??[];
    public Task<PullRequestIntelligence?> GetPullRequestIntelligenceAsync(string owner,string repository,int number,CancellationToken cancellationToken=default)=>GetJsonAsync<PullRequestIntelligence>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/pulls/{number}","GET /repos/{owner}/{repo}/pulls/{number}",cancellationToken);
    public async Task<IReadOnlyList<GitHubPullRequestFile>> GetPullRequestFilesAsync(string owner,string repository,int number,CancellationToken cancellationToken=default)=>await GetJsonAsync<IReadOnlyList<GitHubPullRequestFile>>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/pulls/{number}/files?per_page=100","GET /repos/{owner}/{repo}/pulls/{number}/files",cancellationToken)??[];
    public async Task<IReadOnlyList<string>> GetPullRequestChangedFilesAsync(string owner,string repository,int number,CancellationToken cancellationToken=default)=>(await GetPullRequestFilesAsync(owner,repository,number,cancellationToken)).Select(x=>x.Filename).Where(x=>!string.IsNullOrWhiteSpace(x)).Cast<string>().ToArray();
    public async Task<IReadOnlyList<PullRequestReviewInfo>> GetPullRequestReviewsAsync(string owner,string repository,int number,CancellationToken cancellationToken=default)=>await GetJsonAsync<IReadOnlyList<PullRequestReviewInfo>>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/pulls/{number}/reviews","GET /repos/{owner}/{repo}/pulls/{number}/reviews",cancellationToken)??[];
    public async Task<IReadOnlyList<PullRequestThreadInfo>> GetPullRequestThreadsAsync(string owner,string repository,int number,CancellationToken cancellationToken=default)=>await GetJsonAsync<IReadOnlyList<PullRequestThreadInfo>>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/pulls/{number}/comments","GET /repos/{owner}/{repo}/pulls/{number}/comments",cancellationToken)??[];
    public async Task<string?> GetPullRequestDiffAsync(string owner,string repository,int number,CancellationToken cancellationToken=default){using var request=new HttpRequestMessage(HttpMethod.Get,$"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/pulls/{number}");request.Headers.Accept.Clear();request.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/vnd.github.v3.diff"));var stopwatch=Stopwatch.StartNew();try{using var response=await httpClient.SendAsync(request,cancellationToken);stopwatch.Stop();var status=(int)response.StatusCode;if(!response.IsSuccessStatusCode){var message=$"HTTP {status} {response.ReasonPhrase}";telemetry.Record("GET","GET /repos/{owner}/{repo}/pulls/{number}.diff",status,stopwatch.ElapsedMilliseconds,message);throw new HttpRequestException(message);}var text=await response.Content.ReadAsStringAsync(cancellationToken);telemetry.Record("GET","GET /repos/{owner}/{repo}/pulls/{number}.diff",status,stopwatch.ElapsedMilliseconds);return text;}catch(OperationCanceledException) when(!cancellationToken.IsCancellationRequested){stopwatch.Stop();telemetry.Record("GET","GET /repos/{owner}/{repo}/pulls/{number}.diff",408,stopwatch.ElapsedMilliseconds,"Request timed out");throw;}}
    public async Task<string?> GetPullRequestFilePatchAsync(string owner,string repository,int number,string path,CancellationToken cancellationToken=default)=>(await GetPullRequestFilesAsync(owner,repository,number,cancellationToken)).FirstOrDefault(x=>string.Equals(x.Filename,path,StringComparison.Ordinal))?.Patch;
    public async Task<IReadOnlyList<GitHubCheckRun>> GetCheckRunsAsync(string owner,string repository,string sha,CancellationToken cancellationToken=default)=>await GetJsonAsync<GitHubCheckRunResponse>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/commits/{Uri.EscapeDataString(sha)}/check-runs?per_page=100","GET /repos/{owner}/{repo}/commits/{sha}/check-runs",cancellationToken) is { CheckRuns: var runs } ? runs ?? [] : [];
    public async Task<(string Label,string Detail)> GetCommitStatusAsync(string owner,string repository,string sha,CancellationToken cancellationToken=default){var status=await GetJsonAsync<GitHubCommitStatus>($"/repos/{Uri.EscapeDataString(owner)}/{Uri.EscapeDataString(repository)}/commits/{Uri.EscapeDataString(sha)}/status","GET /repos/{owner}/{repo}/commits/{sha}/status",cancellationToken);if(status is null)return("NOT CHECKED","Commit status is not available.");return status.State switch{"success"=>("PASS","All checks passed."),"failure"=>("FAIL","One or more checks failed."),"pending"=>("PENDING","Checks are still running."),_=>(status.State?.ToUpperInvariant()??"UNKNOWN",$"{status.TotalCount} status checks reported.")};}
    private async Task<T?> GetJsonAsync<T>(string endpoint,string telemetryEndpoint,CancellationToken cancellationToken=default){var stopwatch=Stopwatch.StartNew();try{using var response=await httpClient.GetAsync(endpoint,cancellationToken);stopwatch.Stop();var status=(int)response.StatusCode;if(!response.IsSuccessStatusCode){var message=$"HTTP {status} {response.ReasonPhrase}";telemetry.Record("GET",telemetryEndpoint,status,stopwatch.ElapsedMilliseconds,message);throw new HttpRequestException(message);}var value=await response.Content.ReadFromJsonAsync<T>(cancellationToken:cancellationToken);telemetry.Record("GET",telemetryEndpoint,status,stopwatch.ElapsedMilliseconds);return value;}catch(OperationCanceledException) when(!cancellationToken.IsCancellationRequested){stopwatch.Stop();telemetry.Record("GET",telemetryEndpoint,408,stopwatch.ElapsedMilliseconds,"Request timed out");throw;}catch(HttpRequestException){throw;}catch(System.Text.Json.JsonException ex){stopwatch.Stop();telemetry.Record("GET",telemetryEndpoint,0,stopwatch.ElapsedMilliseconds,ex.Message);throw;}}
}

public sealed record GitHubProfile(string Login,string? Name,string? AvatarUrl,string? HtmlUrl,string? Bio,int PublicRepos,int Followers,int Following);
public sealed record GitHubRepository(string Name,string? Description,string? HtmlUrl,string? Language,int StargazersCount,int ForksCount,bool Fork,DateTimeOffset? UpdatedAt);
public sealed record GitHubReadme(string? Name,string? Path,string? HtmlUrl,string? Content,string? Encoding){[JsonIgnore]public string? DecodedContent{get;init;}}
public sealed record GitHubFileContent(string? Name,string? Path,string? HtmlUrl,string? Content,string? Encoding){[JsonIgnore]public string? DecodedContent{get;init;}}
public sealed record GitHubCommit(string Sha,GitHubCommitDetails? Commit,GitHubUser? Author,string? HtmlUrl);
public sealed record GitHubCommitDetails(GitHubCommitAuthor? Author,string? Message);
public sealed record GitHubCommitAuthor(string? Name,DateTimeOffset? Date);
public sealed record GitHubCommitDetail(string Sha,GitHubCommitDetails? Commit,GitHubUser? Author,string? HtmlUrl,GitHubCommitStats? Stats,IReadOnlyList<GitHubCommitFile>? Files,IReadOnlyList<GitHubCommitParent>? Parents);
public sealed record GitHubCommitParent(string Sha,string? HtmlUrl);
public sealed record GitHubCommitStats(int Additions,int Deletions,int Total);
public sealed record GitHubCommitFile(string? Filename,string? Status,int Additions,int Deletions,int Changes,string? BlobUrl,string? RawUrl,string? Patch);
public sealed record GitHubCompareResult(string Status,int AheadBy,int BehindBy,int TotalCommits,IReadOnlyList<GitHubCommit>? Commits,IReadOnlyList<GitHubCommitFile>? Files);
public sealed record GitHubUser(string? Login,string? AvatarUrl,string? HtmlUrl);
public sealed record GitHubPullRequest(int Number,string? Title,string? HtmlUrl,string? State,bool Draft,DateTimeOffset? UpdatedAt,GitHubUser? User);
public sealed record GitHubIssue(int Number,string? Title,string? HtmlUrl,string? State,DateTimeOffset? UpdatedAt,GitHubUser? User,GitHubPullRequestLink? PullRequest);
public sealed record GitHubPullRequestLink(string? Url);
public sealed record PullRequestIntelligence(int Number,string? Title,string? Body,string? HtmlUrl,string State,bool Draft,string HeadRef,string BaseRef,string HeadSha,int Additions,int Deletions);
public sealed record GitHubPullRequestFile(string? Filename,string? Status,int Additions,int Deletions,int Changes,string? Patch);
public sealed record PullRequestReviewInfo(string? UserLogin,string? State,string? Body,GitHubUserInfo? User);
public sealed record PullRequestThreadInfo(string? Body,string? Path,int? Line,bool IsResolved);
public sealed record GitHubUserInfo(string? Login);
public sealed record GitHubCommitStatus(string? State,int TotalCount);
public sealed record GitHubCheckRun(string? Name,string? Status,string? Conclusion,string? HtmlUrl,DateTimeOffset? StartedAt,DateTimeOffset? CompletedAt);
public sealed record GitHubCheckRunResponse(IReadOnlyList<GitHubCheckRun>? CheckRuns);
